name: CI Pipeline

on:
  workflow_dispatch: {}
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - name:  Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}         # This checks out the branch you selected in the UI

    - name:  Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name:  Install dependencies
      run: npm install

    - name: Create Image Tag
      run: |
          echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "TAG_BUILD=v-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

    - name:  Log in to Docker Hub
      uses:  docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    -   name: build-tag-push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nodejs-app:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/nodejs-app:${{ env.TAG_BUILD }}
  
    - name: update helm values with new tag
      run: |
          sed -i "s/tag: \".*\"/tag: \"${TAG_BUILD}\"/" nodejs-app/values.yaml

    - name: Commit and push updated values.yaml
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add nodejs-app/values.yaml
        git commit -m "Update image tag to ${TAG_BUILD}"
        git push

      
  # Argocd is detect the changes on git repo so i don't need the deploy stage 
  #deploy:
  #   runs-on: self-hosted
  #   steps:
  #   - name: deploy on k8s
  #     run: |
  #       kubectl apply -f k8s/